version: '3'
services:
  express_server:
    build: .
    ports:
      - "${PORT}:${CONTAINER_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  
volumes:
  postgres-data:
